Develop
parkh130/go-jwt pull request #1
Opened 2021-09-07 06:05 UTC by parkh130

2021-09-07 07:25 UTC, pike-kwc commented
reviewになってない

2021-09-07 08:17 UTC, pike-kwc approved these changes

2021-09-07 08:17 UTC, pike-kwc commented on main_test.go
> +// func TestRenderLoginViewHandler(t *testing.T) {
コメント残ってる

2021-09-08 01:04 UTC, te-koyama reviewed
@parkh130 レビューしたので確認をお願いします。

2021-09-08 01:04 UTC, pike-kwc reviewed
CompileDaemonを削除してください。

2021-09-08 01:04 UTC, te-koyama commented on templates/login.html
> +</html>
no newline at end of file があるので修正

2021-09-08 01:05 UTC, pike-kwc requested changes
CompileDaemonを削除してください。

2021-09-08 18:35 UTC, hkpark130 requested changes
TEST

2021-09-08 18:35 UTC, hkpark130 reviewed
TEST2

2021-09-08 18:46 UTC, hkpark130 commented
> TEST

2021-09-10 01:59 UTC, pike-kwc requested changes
.gitmessageを使うのがいいと思う！テンプレートを入れてください！

2021-09-10 01:59 UTC, pike-kwc commented on templates/login.html
> +
勉強のために作ってにると思うけど、<head>にせめて<title>を入れてください。

2021-09-10 01:59 UTC, pike-kwc commented on templates/login.html
> +<html>
<lang>をいれてください。

2021-09-13 22:13 UTC, pike-kwc approved these changes

2021-09-14 01:46 UTC, hkpark130 approved these changes

2021-09-14 02:08 UTC, merged